# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias noderl="env NODE_NO_READLINE=1 rlwrap node"

alias lsc='ls --color=always'
alias lsc1='lsc -1'
alias lsca='lsc -Ah'
alias lsless='lsca | less -R'
alias lsl='lsless'
alias lsal='lsc -lAhF | less -R'

# some more ls aliases
alias la='ls -A'
alias l='ls -CF'
alias l1='ls -1'
alias lall='ls -AlhF'

alias py='python'

alias filecount='echo "$(ls -1 $* | wc -l) files"'

alias user='echo $USERNAME@$HOSTNAME'
alias up='updir'
alias octave='/opt/octave34/bin/octave'
alias davmail='/opt/davmail/davmail.sh /opt/davmail/davmail.properties'
alias cdd='cd ..'
alias home='cd ~/'
alias copydir='echo "$PWD" | xclip'
alias cdclip='cd `xclip -o`'
alias tcfav='truecrypt --auto-mount=favorites'
alias umount-tc='truecrypt -d'
#alias showpath='echo "$PATH" | sed "s/:/\n/g"'
alias lspath='echo "$PATH" | sed "s/:/\n/g"'
alias userps='ps -u offero -o pid,%cpu,%mem,start_time,size=-size-,state,cmd'

alias cpu-set-performance='setgov performance'
alias cpu-set-ondemand='setgov ondemand'

alias vless='vim -u /usr/share/vim/vim74/macros/less.vim'

alias ytdl='youtube-dl --format="bestvideo+bestaudio"'

alias git-br-all='for ref in $(git for-each-ref --sort=-committerdate --format="%(refname)" refs/heads/ refs/remotes ); do git log -n1 $ref --pretty=format:"%Cgreen%cr%Creset %C(yellow)%d%Creset %C(bold blue)<%an>%Creset%n" | cat ; done | awk '"'! a["'$0'"]++'"
